[package]
name = "quaddle-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
gorilla-physics = { path = "../gorilla-physics/"}
esp32rs = {path = "../esp32rs/"}
nalgebra = { version = "0.33", features = [] }
urdf-rs = "0.9.0"
futures = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1"}


[lib]
name = "quaddle"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "main"
path = "src/main.rs"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(rust_analyzer)'] }
