// Import shared CSS
import "chimpanzee-ui/css";

import { initSimulator } from "./sim";
import { getSimulator } from "./sim";
import {
  createSerialMonitorPanel,
  setupResize,
  updateUIforMode,
  createMotionButton,
} from "chimpanzee-ui";

initSimulator();
const panel = createSerialMonitorPanel({ getSimulator });
updateUIforMode();
setupResize();

// Skill names mirror Instinct_Quaddle.h; each payload is "k" + skill name.
const motions = [
  // Gaits
  { payload: "kbbbk", label: "Back Walk" },
  { payload: "kbiped", label: "Biped Walk" },
  { payload: "kbkL", label: "Backward Left Turn" },
  { payload: "kboat", label: "Boat" },
  { payload: "ktiptoeF", label: "Tiptoe" },
  { payload: "kceiling", label: "Walk Upside Down" },
  { payload: "kdance", label: "Dance" },
  { payload: "kdance3F", label: "Dance 3" },
  { payload: "kdance4F", label: "Dance 4" },
  { payload: "kfrontScoot", label: "Front Scoot 0" },
  { payload: "kfrontScoot2", label: "Front Scoot 1" },
  { payload: "khumanoid", label: "Humanoid Walk" },
  { payload: "kpaddle", label: "Paddle" },
  { payload: "kbackScoot", label: "Back Scoot" },
  { payload: "ksideL", label: "Sideways Left" },
  { payload: "kslide", label: "Slide" },
  { payload: "kbdF", label: "Bound Forward" },
  { payload: "kbkF", label: "Backward Walk" },
  { payload: "kbkfast", label: "Backward Fast" },
  { payload: "kbkFast", label: "Backward Fast 2" },
  { payload: "kcircleL", label: "Circle Left 0" },
  { payload: "kcircle2L", label: "Circle Left 1" },
  { payload: "kcircR", label: "Circle Right" },
  { payload: "kcrF", label: "Crawl Forward" },
  { payload: "kcrL", label: "Crawl Left" },
  { payload: "kjmpB", label: "Jump Backward" },
  { payload: "kjmpF", label: "Jump Forward" },
  { payload: "kmarchB", label: "March Backward" },
  { payload: "kmarchF", label: "March Forward" },
  { payload: "knoRightBackF", label: "Three-Leg 0" },
  { payload: "knoRightBackL", label: "Three-Leg Left" },
  { payload: "knoRightBackR", label: "Three-Leg Right" },
  { payload: "knoLeftFrontF", label: "Three-Leg 1" },
  { payload: "komniFL", label: "Omni Forward-Left" },
  { payload: "kOmniR", label: "Omni Right" },
  { payload: "kdragWk2F", label: "Drag Walk 2 Forward" },
  { payload: "kdragWkB", label: "Drag Walk Backward" },
  { payload: "kdragWkF", label: "Drag Walk Forward" },
  { payload: "kside", label: "Sideways" },
  { payload: "ksmallTrF", label: "Small Turn Forward" },
  { payload: "kpaceF", label: "Pace Forward" },
  { payload: "kstep1F", label: "Step 1" },
  { payload: "kstep2F", label: "Step 2" },
  { payload: "kstep3", label: "Step 3" },
  { payload: "kstepDown", label: "Step Down" },
  { payload: "ktr15F", label: "Trot 15 Forward" },
  { payload: "ktr20F", label: "Trot 20 Forward" },
  { payload: "ktrB", label: "Trot Backward" },
  { payload: "ktrF", label: "Trot Forward" },
  { payload: "ktrL", label: "Trot Left" },
  { payload: "kturn1L", label: "Turn 1 Left" },
  { payload: "kturn2L", label: "Turn 2 Left" },
  { payload: "kvt2L", label: "Spin Left Fast" },
  { payload: "kvt90L", label: "Spin 90° Left" },
  { payload: "kvtL", label: "Spin Left" },
  { payload: "kdance1F", label: "Dance 1" },
  { payload: "kdance2F", label: "Dance 2" },
  { payload: "kdance12L", label: "Dance 12 Left" },
  { payload: "kwk20F", label: "Walk 20 Forward" },
  { payload: "kwk0L", label: "Walk Left 0" },
  { payload: "kwkL", label: "Walk Left 1" },
  { payload: "kwk2L", label: "Walk Left 2" },
  { payload: "kwkB", label: "Walk Backward" },
  { payload: "kwkF", label: "Walk Forward" },

  // Behaviors
  { payload: "kbf", label: "Backflip" },
  { payload: "kdropRec", label: "Drop Recovery" },
  { payload: "kff", label: "Frontflip" },
  { payload: "khi", label: "Wave Hi" },
  { payload: "khds", label: "Handstand" },
  { payload: "khsk", label: "Handshake" },
  { payload: "khighbar", label: "High Bar" },
  { payload: "kjumpSlide", label: "Jump Slide" },
  { payload: "kglide", label: "Glide" },
  { payload: "kpee", label: "Pee" },
  { payload: "kpd", label: "Play Dead" },
  { payload: "kpd2", label: "Play Dead (Front Flip)" },
  { payload: "kflipRoll", label: "Flip Roll" },
  { payload: "kpreparation", label: "Preparation" },
  { payload: "krc", label: "Recover" },
  { payload: "krc2", label: "Recover 2" },
  { payload: "krest2up", label: "Rest to Up" },
  { payload: "kscrh", label: "Scratch" },
  { payload: "kts", label: "Test Servo" },
  { payload: "kup2dance", label: "Up to Dance" },
  { payload: "kup2dog", label: "Up to Dog" },
  { payload: "kup2gb", label: "Up to Gameboy" },
  { payload: "kup2rest", label: "Up to Rest" },

  // Postures
  { payload: "kbalance", label: "Balance" },
  { payload: "kbuttUp", label: "Butt Up" },
  { payload: "kcalib", label: "Calibrate" },
  { payload: "kdog", label: "Dog" },
  { payload: "kdropped", label: "Dropped" },
  { payload: "kfButtUp", label: "Front Butt Up" },
  { payload: "kgb", label: "Gameboy" },
  { payload: "klifted", label: "Lifted" },
  { payload: "kqWheel0", label: "Wheel Pose 0" },
  { payload: "kqWheel1", label: "Wheel Pose 1" },
  { payload: "kqWheel2", label: "Wheel Pose 2" },
  { payload: "kqWheel3", label: "Wheel Pose 3" },
  { payload: "kqWheel4", label: "Wheel Pose 4" },
  { payload: "krest", label: "Rest" },
  { payload: "ksit", label: "Sit" },
  { payload: "kstr", label: "Stretch" },
  { payload: "kup", label: "Stand Up" },
  { payload: "kzero", label: "Zero" },
];
for (const { payload, label } of motions) {
  createMotionButton({ getSimulator }, payload, label);
}
